version: '3.8'

services:
  db:
    image: postgres:15
    container_name: auth_db
    env_file:
      - ./auth_service/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auth_user -d auth_db_name"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  chat_db:
    image: postgres:15
    container_name: chat_db
    env_file:
      - ./chat_service/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chat_user -d chat_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - chat_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: auth_redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "6379:6379"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk' 

  auth_service:
    build: ./auth_service
    container_name: django_auth
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./auth_service:/app
    ports:
      - "8000:8000"
    env_file:
      - ./auth_service/.env
    depends_on:
      db:
        condition: service_healthy
      kafka:
        condition: service_started
      redis:
        condition: service_healthy

  auth_worker:
    build: ./auth_service
    container_name: auth_celery_worker
    command: celery -A core worker -l info --pool=solo
    volumes:
      - ./auth_service:/app
    env_file:
      - ./auth_service/.env
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
      kafka:
        condition: service_started

  chat_service:
    build: ./chat_service
    container_name: django_chat
    command: >
      sh -c "python manage.py migrate &&
             daphne -b 0.0.0.0 -p 8001 core.asgi:application"
    volumes:
      - ./chat_service:/app
    ports:
      - "8001:8001"
    env_file:
      - ./chat_service/.env 
    depends_on:
      chat_db:
        condition: service_healthy
      kafka:
        condition: service_started
      redis:
        condition: service_healthy

  chat_notifications_consumer:
    build: ./chat_service
    container_name: kafka_consumer_worker
    command: sh -c "sleep 15 && python -u manage.py run_kafka_consumer"
    restart: on-failure
    volumes:
      - ./chat_service:/app
    env_file:
      - ./chat_service/.env
    depends_on:
      kafka:
        condition: service_started
      redis:
        condition: service_healthy

  chat_messages_notifications:
    build: ./chat_service
    container_name: chat_notifications_worker
    command: sh -c "sleep 15 && python manage.py run_notifications_consumer"
    volumes:
      - ./chat_service:/app
    env_file:
      - ./chat_service/.env
    depends_on:
      kafka:
        condition: service_started
      redis:
        condition: service_healthy
  minio:
    image: minio/minio
    container_name: media_storage
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "media_admin"
      MINIO_ROOT_PASSWORD: "media_password"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
  media_service:
    build: ./media_service
    container_name: fastapi_media
    command: sh -c "sleep 15 && uvicorn main:app --host 0.0.0.0 --port 8002"
    ports:
      - "8002:8002"
    env_file:
      - ./media_service/.env
    depends_on:
      - minio
    volumes:
      - ./media_service:/app
  media_processor_go:
    build: ./media_processor_go
    container_name: go_thumbnailer
    environment:
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=media_admin
      - MINIO_SECRET_KEY=media_password
    depends_on:
      - kafka
      - minio
    # volumes:
    #   - ./media_processor_go:/app

volumes:
  postgres_data:
  chat_data:
  minio_data: